version: "3.8"

services:
  server:
    build:
      context: .
      target: build
    volumes:
      - ./src:/src
      - ./go.mod:/go.mod
      - ./go.sum:/go.sum
    working_dir: /src
    command: go run main.go
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # <--- вот это добавь

volumes:
  db-data:
